// client-side enhancements: simple search/filter for v3 (run on pages generated by build.py)
(function(){
  function init(){
    const search = document.querySelector('#searchInput');
    if(!search) return;
    search.addEventListener('input', function(e){
      const q = e.target.value.toLowerCase();
      document.querySelectorAll('.icons a').forEach(a=>{
        const txt = (a.dataset.tags||'').toLowerCase();
        a.style.display = txt.includes(q)?'inline-block':'none';
      });
    });
  }
  document.addEventListener('DOMContentLoaded', init);
})();
